// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnePieceAPI.Data;

#nullable disable

namespace OnePieceAPI.Migrations
{
    [DbContext(typeof(OnePieceContext))]
    [Migration("20250811134711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnePieceAPI.Models.FrutaDelDiablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("FrutasDelDiablo");
                });

            modelBuilder.Entity("OnePieceAPI.Models.Pirata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FrutaDelDiabloId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Recompensa")
                        .HasColumnType("bigint");

                    b.Property<int?>("TripulacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrutaDelDiabloId");

                    b.HasIndex("TripulacionId");

                    b.ToTable("Piratas");
                });

            modelBuilder.Entity("OnePieceAPI.Models.Tripulacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapitanId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("RecompensaTotal")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CapitanId");

                    b.ToTable("Tripulaciones");
                });

            modelBuilder.Entity("OnePieceAPI.Models.Pirata", b =>
                {
                    b.HasOne("OnePieceAPI.Models.FrutaDelDiablo", "FrutaDelDiablo")
                        .WithMany()
                        .HasForeignKey("FrutaDelDiabloId");

                    b.HasOne("OnePieceAPI.Models.Tripulacion", "Tripulacion")
                        .WithMany("Miembros")
                        .HasForeignKey("TripulacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FrutaDelDiablo");

                    b.Navigation("Tripulacion");
                });

            modelBuilder.Entity("OnePieceAPI.Models.Tripulacion", b =>
                {
                    b.HasOne("OnePieceAPI.Models.Pirata", "Capitan")
                        .WithMany()
                        .HasForeignKey("CapitanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Capitan");
                });

            modelBuilder.Entity("OnePieceAPI.Models.Tripulacion", b =>
                {
                    b.Navigation("Miembros");
                });
#pragma warning restore 612, 618
        }
    }
}
