// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnePieceAPI.Data;

#nullable disable

namespace OnePieceAPI.Migrations
{
    [DbContext(typeof(OnePieceContext))]
    [Migration("20250604173023_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnePieceAPI.Models.FrutaDelDiablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FrutasDelDiablo");
                });

            modelBuilder.Entity("OnePieceAPI.Models.Pirata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("FrutaDelDiabloId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Recompensa")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FrutaDelDiabloId");

                    b.ToTable("Piratas");
                });

            modelBuilder.Entity("OnePieceAPI.Models.Pirata", b =>
                {
                    b.HasOne("OnePieceAPI.Models.FrutaDelDiablo", "FrutaDelDiablo")
                        .WithMany()
                        .HasForeignKey("FrutaDelDiabloId");

                    b.Navigation("FrutaDelDiablo");
                });
#pragma warning restore 612, 618
        }
    }
}
